# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('some_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='update_time',
            new_name='url',
        ),
    ]
